[project]
name = "azure-days"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework-core>=1.0.0b260107",
    "python-dotenv>=1.2.1",
]
